language: ruby
cache: bundler
bundler_args: --path ../../vendor/bundle
before_install:
  - gem update bundler
rvm:
  - 2.2.2
  - 1.9.3
  - jruby
gemfile:
  - spec/gemfiles/Gemfile.rails-3.2
  - spec/gemfiles/Gemfile.rails-4.0
  - spec/gemfiles/Gemfile.rails-4.1
  - spec/gemfiles/Gemfile.rails-4.2
  - Gemfile
script: bundle exec rspec
