language: ruby
cache: bundler
bundler_args: --path ../../vendor/bundle
rvm:
  - 2.3.1
  - jruby-9000
gemfile:
  - spec/gemfiles/Gemfile.rails-3.2
  - spec/gemfiles/Gemfile.rails-4.0
  - spec/gemfiles/Gemfile.rails-4.1
  - spec/gemfiles/Gemfile.rails-4.2
  - Gemfile
script: bundle exec rspec
